/* Generated by Yosys 0.9+4052 (git sha1 0ccc7229c, gcc 10.2.0 -march=x86-64 -mtune=generic -O2 -fno-plt -fPIC -Os) */

(* \nmigen.hierarchy  = "myip1.U$$0" *)
(* generator = "nMigen" *)
module \U$$0 (shift_clk, reset);
  reg \initial  = 0;
  (* src = "/home/konrad/dev/litex/nmigen/nmigen/lib/cdc.py:163" *)
  wire async_ff_clk;
  (* src = "/home/konrad/dev/litex/nmigen/nmigen/lib/cdc.py:163" *)
  wire async_ff_rst;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:317" *)
  input reset;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:322" *)
  input shift_clk;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:322" *)
  wire shift_rst;
  (* src = "/home/konrad/dev/litex/nmigen/nmigen/lib/cdc.py:164" *)
  reg stage0 = 1'h1;
  (* src = "/home/konrad/dev/litex/nmigen/nmigen/lib/cdc.py:164" *)
  reg \stage0$next ;
  (* src = "/home/konrad/dev/litex/nmigen/nmigen/lib/cdc.py:164" *)
  reg stage1 = 1'h1;
  (* src = "/home/konrad/dev/litex/nmigen/nmigen/lib/cdc.py:164" *)
  reg \stage1$next ;
  always @(posedge async_ff_clk, posedge async_ff_rst)
    if (async_ff_rst) stage1 <= 1'h1;
    else stage1 <= \stage1$next ;
  always @(posedge async_ff_clk, posedge async_ff_rst)
    if (async_ff_rst) stage0 <= 1'h1;
    else stage0 <= \stage0$next ;
  always @* begin
    if (\initial ) begin end
    \stage0$next  = 1'h0;
  end
  always @* begin
    if (\initial ) begin end
    \stage1$next  = stage0;
  end
  assign shift_rst = stage1;
  assign async_ff_clk = shift_clk;
  assign async_ff_rst = reset;
endmodule

(* \nmigen.hierarchy  = "myip1" *)
(* top =  1  *)
(* generator = "nMigen" *)
module myip1(shift_clk, buf_io_out, wb__adr, wb__dat_w, wb__dat_r, wb__sel, wb__cyc, wb__stb, wb__we, wb__ack, sel, clk, rst, reset);
  reg \initial  = 0;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *)
  wire \$10 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" *)
  wire \$12 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *)
  wire \$14 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *)
  wire \$16 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" *)
  wire \$18 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *)
  wire \$2 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *)
  wire \$20 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *)
  wire \$22 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" *)
  wire \$24 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *)
  wire \$26 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *)
  wire \$28 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" *)
  wire \$30 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *)
  wire \$32 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *)
  wire \$34 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" *)
  wire \$36 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:293" *)
  wire [31:0] \$38 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *)
  wire \$4 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *)
  wire \$40 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *)
  wire \$42 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" *)
  wire \$44 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:333" *)
  wire \$46 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:336" *)
  wire \$48 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:339" *)
  wire \$50 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:342" *)
  wire \$52 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" *)
  wire \$6 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *)
  wire \$8 ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:289" *)
  reg ack_r = 1'h0;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:289" *)
  reg \ack_r$next ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:328" *)
  output [7:0] buf_io_out;
  (* src = "/home/konrad/dev/litex/nmigen/nmigen/hdl/ir.py:526" *)
  input clk;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:245" *)
  wire [2:0] dvid_out;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:244" *)
  wire dvid_out_clk;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:293" *)
  reg [9:0] fb_r_addr;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:293" *)
  wire fb_r_data;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:294" *)
  reg [9:0] fb_w_addr;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:294" *)
  reg fb_w_data;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:294" *)
  reg fb_w_en;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:317" *)
  input reset;
  (* src = "/home/konrad/dev/litex/nmigen/nmigen/hdl/ir.py:526" *)
  output rst;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:325" *)
  input [3:0] sel;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:322" *)
  input shift_clk;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:272" *)
  output wb__ack;
  reg wb__ack = 1'h0;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:272" *)
  reg \wb__ack$next ;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:272" *)
  input [31:0] wb__adr;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:272" *)
  input wb__cyc;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:272" *)
  output [31:0] wb__dat_r;
  reg [31:0] wb__dat_r;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:272" *)
  input [31:0] wb__dat_w;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:272" *)
  input wb__sel;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:272" *)
  input wb__stb;
  (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:272" *)
  input wb__we;
  reg [0:0] fb [1023:0];
  initial begin
    fb[0] = 1'h0;
    fb[1] = 1'h0;
    fb[2] = 1'h0;
    fb[3] = 1'h0;
    fb[4] = 1'h0;
    fb[5] = 1'h0;
    fb[6] = 1'h0;
    fb[7] = 1'h0;
    fb[8] = 1'h0;
    fb[9] = 1'h0;
    fb[10] = 1'h0;
    fb[11] = 1'h0;
    fb[12] = 1'h0;
    fb[13] = 1'h0;
    fb[14] = 1'h0;
    fb[15] = 1'h0;
    fb[16] = 1'h0;
    fb[17] = 1'h0;
    fb[18] = 1'h0;
    fb[19] = 1'h0;
    fb[20] = 1'h0;
    fb[21] = 1'h0;
    fb[22] = 1'h0;
    fb[23] = 1'h0;
    fb[24] = 1'h0;
    fb[25] = 1'h0;
    fb[26] = 1'h0;
    fb[27] = 1'h0;
    fb[28] = 1'h0;
    fb[29] = 1'h0;
    fb[30] = 1'h0;
    fb[31] = 1'h0;
    fb[32] = 1'h0;
    fb[33] = 1'h0;
    fb[34] = 1'h0;
    fb[35] = 1'h0;
    fb[36] = 1'h0;
    fb[37] = 1'h0;
    fb[38] = 1'h0;
    fb[39] = 1'h0;
    fb[40] = 1'h0;
    fb[41] = 1'h0;
    fb[42] = 1'h0;
    fb[43] = 1'h0;
    fb[44] = 1'h0;
    fb[45] = 1'h0;
    fb[46] = 1'h0;
    fb[47] = 1'h0;
    fb[48] = 1'h0;
    fb[49] = 1'h0;
    fb[50] = 1'h0;
    fb[51] = 1'h0;
    fb[52] = 1'h0;
    fb[53] = 1'h0;
    fb[54] = 1'h0;
    fb[55] = 1'h0;
    fb[56] = 1'h0;
    fb[57] = 1'h0;
    fb[58] = 1'h0;
    fb[59] = 1'h0;
    fb[60] = 1'h0;
    fb[61] = 1'h0;
    fb[62] = 1'h0;
    fb[63] = 1'h0;
    fb[64] = 1'h0;
    fb[65] = 1'h0;
    fb[66] = 1'h0;
    fb[67] = 1'h0;
    fb[68] = 1'h0;
    fb[69] = 1'h0;
    fb[70] = 1'h0;
    fb[71] = 1'h0;
    fb[72] = 1'h0;
    fb[73] = 1'h0;
    fb[74] = 1'h0;
    fb[75] = 1'h0;
    fb[76] = 1'h0;
    fb[77] = 1'h0;
    fb[78] = 1'h0;
    fb[79] = 1'h0;
    fb[80] = 1'h0;
    fb[81] = 1'h0;
    fb[82] = 1'h0;
    fb[83] = 1'h0;
    fb[84] = 1'h0;
    fb[85] = 1'h0;
    fb[86] = 1'h0;
    fb[87] = 1'h0;
    fb[88] = 1'h0;
    fb[89] = 1'h0;
    fb[90] = 1'h0;
    fb[91] = 1'h0;
    fb[92] = 1'h0;
    fb[93] = 1'h0;
    fb[94] = 1'h0;
    fb[95] = 1'h0;
    fb[96] = 1'h0;
    fb[97] = 1'h0;
    fb[98] = 1'h0;
    fb[99] = 1'h0;
    fb[100] = 1'h0;
    fb[101] = 1'h0;
    fb[102] = 1'h0;
    fb[103] = 1'h0;
    fb[104] = 1'h0;
    fb[105] = 1'h0;
    fb[106] = 1'h0;
    fb[107] = 1'h0;
    fb[108] = 1'h0;
    fb[109] = 1'h0;
    fb[110] = 1'h0;
    fb[111] = 1'h0;
    fb[112] = 1'h0;
    fb[113] = 1'h0;
    fb[114] = 1'h0;
    fb[115] = 1'h0;
    fb[116] = 1'h0;
    fb[117] = 1'h0;
    fb[118] = 1'h0;
    fb[119] = 1'h0;
    fb[120] = 1'h0;
    fb[121] = 1'h0;
    fb[122] = 1'h0;
    fb[123] = 1'h0;
    fb[124] = 1'h0;
    fb[125] = 1'h0;
    fb[126] = 1'h0;
    fb[127] = 1'h0;
    fb[128] = 1'h0;
    fb[129] = 1'h0;
    fb[130] = 1'h0;
    fb[131] = 1'h0;
    fb[132] = 1'h0;
    fb[133] = 1'h0;
    fb[134] = 1'h0;
    fb[135] = 1'h0;
    fb[136] = 1'h0;
    fb[137] = 1'h0;
    fb[138] = 1'h0;
    fb[139] = 1'h0;
    fb[140] = 1'h0;
    fb[141] = 1'h0;
    fb[142] = 1'h0;
    fb[143] = 1'h0;
    fb[144] = 1'h0;
    fb[145] = 1'h0;
    fb[146] = 1'h0;
    fb[147] = 1'h0;
    fb[148] = 1'h0;
    fb[149] = 1'h0;
    fb[150] = 1'h0;
    fb[151] = 1'h0;
    fb[152] = 1'h0;
    fb[153] = 1'h0;
    fb[154] = 1'h0;
    fb[155] = 1'h0;
    fb[156] = 1'h0;
    fb[157] = 1'h0;
    fb[158] = 1'h0;
    fb[159] = 1'h0;
    fb[160] = 1'h0;
    fb[161] = 1'h0;
    fb[162] = 1'h0;
    fb[163] = 1'h0;
    fb[164] = 1'h0;
    fb[165] = 1'h0;
    fb[166] = 1'h0;
    fb[167] = 1'h0;
    fb[168] = 1'h0;
    fb[169] = 1'h0;
    fb[170] = 1'h0;
    fb[171] = 1'h0;
    fb[172] = 1'h0;
    fb[173] = 1'h0;
    fb[174] = 1'h0;
    fb[175] = 1'h0;
    fb[176] = 1'h0;
    fb[177] = 1'h0;
    fb[178] = 1'h0;
    fb[179] = 1'h0;
    fb[180] = 1'h0;
    fb[181] = 1'h0;
    fb[182] = 1'h0;
    fb[183] = 1'h0;
    fb[184] = 1'h0;
    fb[185] = 1'h0;
    fb[186] = 1'h0;
    fb[187] = 1'h0;
    fb[188] = 1'h0;
    fb[189] = 1'h0;
    fb[190] = 1'h0;
    fb[191] = 1'h0;
    fb[192] = 1'h0;
    fb[193] = 1'h0;
    fb[194] = 1'h0;
    fb[195] = 1'h0;
    fb[196] = 1'h0;
    fb[197] = 1'h0;
    fb[198] = 1'h0;
    fb[199] = 1'h0;
    fb[200] = 1'h0;
    fb[201] = 1'h0;
    fb[202] = 1'h0;
    fb[203] = 1'h0;
    fb[204] = 1'h0;
    fb[205] = 1'h0;
    fb[206] = 1'h0;
    fb[207] = 1'h0;
    fb[208] = 1'h0;
    fb[209] = 1'h0;
    fb[210] = 1'h0;
    fb[211] = 1'h0;
    fb[212] = 1'h0;
    fb[213] = 1'h0;
    fb[214] = 1'h0;
    fb[215] = 1'h0;
    fb[216] = 1'h0;
    fb[217] = 1'h0;
    fb[218] = 1'h0;
    fb[219] = 1'h0;
    fb[220] = 1'h0;
    fb[221] = 1'h0;
    fb[222] = 1'h0;
    fb[223] = 1'h0;
    fb[224] = 1'h0;
    fb[225] = 1'h0;
    fb[226] = 1'h0;
    fb[227] = 1'h0;
    fb[228] = 1'h0;
    fb[229] = 1'h0;
    fb[230] = 1'h0;
    fb[231] = 1'h0;
    fb[232] = 1'h0;
    fb[233] = 1'h0;
    fb[234] = 1'h0;
    fb[235] = 1'h0;
    fb[236] = 1'h0;
    fb[237] = 1'h0;
    fb[238] = 1'h0;
    fb[239] = 1'h0;
    fb[240] = 1'h0;
    fb[241] = 1'h0;
    fb[242] = 1'h0;
    fb[243] = 1'h0;
    fb[244] = 1'h0;
    fb[245] = 1'h0;
    fb[246] = 1'h0;
    fb[247] = 1'h0;
    fb[248] = 1'h0;
    fb[249] = 1'h0;
    fb[250] = 1'h0;
    fb[251] = 1'h0;
    fb[252] = 1'h0;
    fb[253] = 1'h0;
    fb[254] = 1'h0;
    fb[255] = 1'h0;
    fb[256] = 1'h0;
    fb[257] = 1'h0;
    fb[258] = 1'h0;
    fb[259] = 1'h0;
    fb[260] = 1'h0;
    fb[261] = 1'h0;
    fb[262] = 1'h0;
    fb[263] = 1'h0;
    fb[264] = 1'h0;
    fb[265] = 1'h0;
    fb[266] = 1'h0;
    fb[267] = 1'h0;
    fb[268] = 1'h0;
    fb[269] = 1'h0;
    fb[270] = 1'h0;
    fb[271] = 1'h0;
    fb[272] = 1'h0;
    fb[273] = 1'h0;
    fb[274] = 1'h0;
    fb[275] = 1'h0;
    fb[276] = 1'h0;
    fb[277] = 1'h0;
    fb[278] = 1'h0;
    fb[279] = 1'h0;
    fb[280] = 1'h0;
    fb[281] = 1'h0;
    fb[282] = 1'h0;
    fb[283] = 1'h0;
    fb[284] = 1'h0;
    fb[285] = 1'h0;
    fb[286] = 1'h0;
    fb[287] = 1'h0;
    fb[288] = 1'h0;
    fb[289] = 1'h0;
    fb[290] = 1'h0;
    fb[291] = 1'h0;
    fb[292] = 1'h0;
    fb[293] = 1'h0;
    fb[294] = 1'h0;
    fb[295] = 1'h0;
    fb[296] = 1'h0;
    fb[297] = 1'h0;
    fb[298] = 1'h0;
    fb[299] = 1'h0;
    fb[300] = 1'h0;
    fb[301] = 1'h0;
    fb[302] = 1'h0;
    fb[303] = 1'h0;
    fb[304] = 1'h0;
    fb[305] = 1'h0;
    fb[306] = 1'h0;
    fb[307] = 1'h0;
    fb[308] = 1'h0;
    fb[309] = 1'h0;
    fb[310] = 1'h0;
    fb[311] = 1'h0;
    fb[312] = 1'h0;
    fb[313] = 1'h0;
    fb[314] = 1'h0;
    fb[315] = 1'h0;
    fb[316] = 1'h0;
    fb[317] = 1'h0;
    fb[318] = 1'h0;
    fb[319] = 1'h0;
    fb[320] = 1'h0;
    fb[321] = 1'h0;
    fb[322] = 1'h0;
    fb[323] = 1'h0;
    fb[324] = 1'h0;
    fb[325] = 1'h0;
    fb[326] = 1'h0;
    fb[327] = 1'h0;
    fb[328] = 1'h0;
    fb[329] = 1'h0;
    fb[330] = 1'h0;
    fb[331] = 1'h0;
    fb[332] = 1'h0;
    fb[333] = 1'h0;
    fb[334] = 1'h0;
    fb[335] = 1'h0;
    fb[336] = 1'h0;
    fb[337] = 1'h0;
    fb[338] = 1'h0;
    fb[339] = 1'h0;
    fb[340] = 1'h0;
    fb[341] = 1'h0;
    fb[342] = 1'h0;
    fb[343] = 1'h0;
    fb[344] = 1'h0;
    fb[345] = 1'h0;
    fb[346] = 1'h0;
    fb[347] = 1'h0;
    fb[348] = 1'h0;
    fb[349] = 1'h0;
    fb[350] = 1'h0;
    fb[351] = 1'h0;
    fb[352] = 1'h0;
    fb[353] = 1'h0;
    fb[354] = 1'h0;
    fb[355] = 1'h0;
    fb[356] = 1'h0;
    fb[357] = 1'h0;
    fb[358] = 1'h0;
    fb[359] = 1'h0;
    fb[360] = 1'h0;
    fb[361] = 1'h0;
    fb[362] = 1'h0;
    fb[363] = 1'h0;
    fb[364] = 1'h0;
    fb[365] = 1'h0;
    fb[366] = 1'h0;
    fb[367] = 1'h0;
    fb[368] = 1'h0;
    fb[369] = 1'h0;
    fb[370] = 1'h0;
    fb[371] = 1'h0;
    fb[372] = 1'h0;
    fb[373] = 1'h0;
    fb[374] = 1'h0;
    fb[375] = 1'h0;
    fb[376] = 1'h0;
    fb[377] = 1'h0;
    fb[378] = 1'h0;
    fb[379] = 1'h0;
    fb[380] = 1'h0;
    fb[381] = 1'h0;
    fb[382] = 1'h0;
    fb[383] = 1'h0;
    fb[384] = 1'h0;
    fb[385] = 1'h0;
    fb[386] = 1'h0;
    fb[387] = 1'h0;
    fb[388] = 1'h0;
    fb[389] = 1'h0;
    fb[390] = 1'h0;
    fb[391] = 1'h0;
    fb[392] = 1'h0;
    fb[393] = 1'h0;
    fb[394] = 1'h0;
    fb[395] = 1'h0;
    fb[396] = 1'h0;
    fb[397] = 1'h0;
    fb[398] = 1'h0;
    fb[399] = 1'h0;
    fb[400] = 1'h0;
    fb[401] = 1'h0;
    fb[402] = 1'h0;
    fb[403] = 1'h0;
    fb[404] = 1'h0;
    fb[405] = 1'h0;
    fb[406] = 1'h0;
    fb[407] = 1'h0;
    fb[408] = 1'h0;
    fb[409] = 1'h0;
    fb[410] = 1'h0;
    fb[411] = 1'h0;
    fb[412] = 1'h0;
    fb[413] = 1'h0;
    fb[414] = 1'h0;
    fb[415] = 1'h0;
    fb[416] = 1'h0;
    fb[417] = 1'h0;
    fb[418] = 1'h0;
    fb[419] = 1'h0;
    fb[420] = 1'h0;
    fb[421] = 1'h0;
    fb[422] = 1'h0;
    fb[423] = 1'h0;
    fb[424] = 1'h0;
    fb[425] = 1'h0;
    fb[426] = 1'h0;
    fb[427] = 1'h0;
    fb[428] = 1'h0;
    fb[429] = 1'h0;
    fb[430] = 1'h0;
    fb[431] = 1'h0;
    fb[432] = 1'h0;
    fb[433] = 1'h0;
    fb[434] = 1'h0;
    fb[435] = 1'h0;
    fb[436] = 1'h0;
    fb[437] = 1'h0;
    fb[438] = 1'h0;
    fb[439] = 1'h0;
    fb[440] = 1'h0;
    fb[441] = 1'h0;
    fb[442] = 1'h0;
    fb[443] = 1'h0;
    fb[444] = 1'h0;
    fb[445] = 1'h0;
    fb[446] = 1'h0;
    fb[447] = 1'h0;
    fb[448] = 1'h0;
    fb[449] = 1'h0;
    fb[450] = 1'h0;
    fb[451] = 1'h0;
    fb[452] = 1'h0;
    fb[453] = 1'h0;
    fb[454] = 1'h0;
    fb[455] = 1'h0;
    fb[456] = 1'h0;
    fb[457] = 1'h0;
    fb[458] = 1'h0;
    fb[459] = 1'h0;
    fb[460] = 1'h0;
    fb[461] = 1'h0;
    fb[462] = 1'h0;
    fb[463] = 1'h0;
    fb[464] = 1'h0;
    fb[465] = 1'h0;
    fb[466] = 1'h0;
    fb[467] = 1'h0;
    fb[468] = 1'h0;
    fb[469] = 1'h0;
    fb[470] = 1'h0;
    fb[471] = 1'h0;
    fb[472] = 1'h0;
    fb[473] = 1'h0;
    fb[474] = 1'h0;
    fb[475] = 1'h0;
    fb[476] = 1'h0;
    fb[477] = 1'h0;
    fb[478] = 1'h0;
    fb[479] = 1'h0;
    fb[480] = 1'h0;
    fb[481] = 1'h0;
    fb[482] = 1'h0;
    fb[483] = 1'h0;
    fb[484] = 1'h0;
    fb[485] = 1'h0;
    fb[486] = 1'h0;
    fb[487] = 1'h0;
    fb[488] = 1'h0;
    fb[489] = 1'h0;
    fb[490] = 1'h0;
    fb[491] = 1'h0;
    fb[492] = 1'h0;
    fb[493] = 1'h0;
    fb[494] = 1'h0;
    fb[495] = 1'h0;
    fb[496] = 1'h0;
    fb[497] = 1'h0;
    fb[498] = 1'h0;
    fb[499] = 1'h0;
    fb[500] = 1'h0;
    fb[501] = 1'h0;
    fb[502] = 1'h0;
    fb[503] = 1'h0;
    fb[504] = 1'h0;
    fb[505] = 1'h0;
    fb[506] = 1'h0;
    fb[507] = 1'h0;
    fb[508] = 1'h0;
    fb[509] = 1'h0;
    fb[510] = 1'h0;
    fb[511] = 1'h0;
    fb[512] = 1'h0;
    fb[513] = 1'h0;
    fb[514] = 1'h0;
    fb[515] = 1'h0;
    fb[516] = 1'h0;
    fb[517] = 1'h0;
    fb[518] = 1'h0;
    fb[519] = 1'h0;
    fb[520] = 1'h0;
    fb[521] = 1'h0;
    fb[522] = 1'h0;
    fb[523] = 1'h0;
    fb[524] = 1'h0;
    fb[525] = 1'h0;
    fb[526] = 1'h0;
    fb[527] = 1'h0;
    fb[528] = 1'h0;
    fb[529] = 1'h0;
    fb[530] = 1'h0;
    fb[531] = 1'h0;
    fb[532] = 1'h0;
    fb[533] = 1'h0;
    fb[534] = 1'h0;
    fb[535] = 1'h0;
    fb[536] = 1'h0;
    fb[537] = 1'h0;
    fb[538] = 1'h0;
    fb[539] = 1'h0;
    fb[540] = 1'h0;
    fb[541] = 1'h0;
    fb[542] = 1'h0;
    fb[543] = 1'h0;
    fb[544] = 1'h0;
    fb[545] = 1'h0;
    fb[546] = 1'h0;
    fb[547] = 1'h0;
    fb[548] = 1'h0;
    fb[549] = 1'h0;
    fb[550] = 1'h0;
    fb[551] = 1'h0;
    fb[552] = 1'h0;
    fb[553] = 1'h0;
    fb[554] = 1'h0;
    fb[555] = 1'h0;
    fb[556] = 1'h0;
    fb[557] = 1'h0;
    fb[558] = 1'h0;
    fb[559] = 1'h0;
    fb[560] = 1'h0;
    fb[561] = 1'h0;
    fb[562] = 1'h0;
    fb[563] = 1'h0;
    fb[564] = 1'h0;
    fb[565] = 1'h0;
    fb[566] = 1'h0;
    fb[567] = 1'h0;
    fb[568] = 1'h0;
    fb[569] = 1'h0;
    fb[570] = 1'h0;
    fb[571] = 1'h0;
    fb[572] = 1'h0;
    fb[573] = 1'h0;
    fb[574] = 1'h0;
    fb[575] = 1'h0;
    fb[576] = 1'h0;
    fb[577] = 1'h0;
    fb[578] = 1'h0;
    fb[579] = 1'h0;
    fb[580] = 1'h0;
    fb[581] = 1'h0;
    fb[582] = 1'h0;
    fb[583] = 1'h0;
    fb[584] = 1'h0;
    fb[585] = 1'h0;
    fb[586] = 1'h0;
    fb[587] = 1'h0;
    fb[588] = 1'h0;
    fb[589] = 1'h0;
    fb[590] = 1'h0;
    fb[591] = 1'h0;
    fb[592] = 1'h0;
    fb[593] = 1'h0;
    fb[594] = 1'h0;
    fb[595] = 1'h0;
    fb[596] = 1'h0;
    fb[597] = 1'h0;
    fb[598] = 1'h0;
    fb[599] = 1'h0;
    fb[600] = 1'h0;
    fb[601] = 1'h0;
    fb[602] = 1'h0;
    fb[603] = 1'h0;
    fb[604] = 1'h0;
    fb[605] = 1'h0;
    fb[606] = 1'h0;
    fb[607] = 1'h0;
    fb[608] = 1'h0;
    fb[609] = 1'h0;
    fb[610] = 1'h0;
    fb[611] = 1'h0;
    fb[612] = 1'h0;
    fb[613] = 1'h0;
    fb[614] = 1'h0;
    fb[615] = 1'h0;
    fb[616] = 1'h0;
    fb[617] = 1'h0;
    fb[618] = 1'h0;
    fb[619] = 1'h0;
    fb[620] = 1'h0;
    fb[621] = 1'h0;
    fb[622] = 1'h0;
    fb[623] = 1'h0;
    fb[624] = 1'h0;
    fb[625] = 1'h0;
    fb[626] = 1'h0;
    fb[627] = 1'h0;
    fb[628] = 1'h0;
    fb[629] = 1'h0;
    fb[630] = 1'h0;
    fb[631] = 1'h0;
    fb[632] = 1'h0;
    fb[633] = 1'h0;
    fb[634] = 1'h0;
    fb[635] = 1'h0;
    fb[636] = 1'h0;
    fb[637] = 1'h0;
    fb[638] = 1'h0;
    fb[639] = 1'h0;
    fb[640] = 1'h0;
    fb[641] = 1'h0;
    fb[642] = 1'h0;
    fb[643] = 1'h0;
    fb[644] = 1'h0;
    fb[645] = 1'h0;
    fb[646] = 1'h0;
    fb[647] = 1'h0;
    fb[648] = 1'h0;
    fb[649] = 1'h0;
    fb[650] = 1'h0;
    fb[651] = 1'h0;
    fb[652] = 1'h0;
    fb[653] = 1'h0;
    fb[654] = 1'h0;
    fb[655] = 1'h0;
    fb[656] = 1'h0;
    fb[657] = 1'h0;
    fb[658] = 1'h0;
    fb[659] = 1'h0;
    fb[660] = 1'h0;
    fb[661] = 1'h0;
    fb[662] = 1'h0;
    fb[663] = 1'h0;
    fb[664] = 1'h0;
    fb[665] = 1'h0;
    fb[666] = 1'h0;
    fb[667] = 1'h0;
    fb[668] = 1'h0;
    fb[669] = 1'h0;
    fb[670] = 1'h0;
    fb[671] = 1'h0;
    fb[672] = 1'h0;
    fb[673] = 1'h0;
    fb[674] = 1'h0;
    fb[675] = 1'h0;
    fb[676] = 1'h0;
    fb[677] = 1'h0;
    fb[678] = 1'h0;
    fb[679] = 1'h0;
    fb[680] = 1'h0;
    fb[681] = 1'h0;
    fb[682] = 1'h0;
    fb[683] = 1'h0;
    fb[684] = 1'h0;
    fb[685] = 1'h0;
    fb[686] = 1'h0;
    fb[687] = 1'h0;
    fb[688] = 1'h0;
    fb[689] = 1'h0;
    fb[690] = 1'h0;
    fb[691] = 1'h0;
    fb[692] = 1'h0;
    fb[693] = 1'h0;
    fb[694] = 1'h0;
    fb[695] = 1'h0;
    fb[696] = 1'h0;
    fb[697] = 1'h0;
    fb[698] = 1'h0;
    fb[699] = 1'h0;
    fb[700] = 1'h0;
    fb[701] = 1'h0;
    fb[702] = 1'h0;
    fb[703] = 1'h0;
    fb[704] = 1'h0;
    fb[705] = 1'h0;
    fb[706] = 1'h0;
    fb[707] = 1'h0;
    fb[708] = 1'h0;
    fb[709] = 1'h0;
    fb[710] = 1'h0;
    fb[711] = 1'h0;
    fb[712] = 1'h0;
    fb[713] = 1'h0;
    fb[714] = 1'h0;
    fb[715] = 1'h0;
    fb[716] = 1'h0;
    fb[717] = 1'h0;
    fb[718] = 1'h0;
    fb[719] = 1'h0;
    fb[720] = 1'h0;
    fb[721] = 1'h0;
    fb[722] = 1'h0;
    fb[723] = 1'h0;
    fb[724] = 1'h0;
    fb[725] = 1'h0;
    fb[726] = 1'h0;
    fb[727] = 1'h0;
    fb[728] = 1'h0;
    fb[729] = 1'h0;
    fb[730] = 1'h0;
    fb[731] = 1'h0;
    fb[732] = 1'h0;
    fb[733] = 1'h0;
    fb[734] = 1'h0;
    fb[735] = 1'h0;
    fb[736] = 1'h0;
    fb[737] = 1'h0;
    fb[738] = 1'h0;
    fb[739] = 1'h0;
    fb[740] = 1'h0;
    fb[741] = 1'h0;
    fb[742] = 1'h0;
    fb[743] = 1'h0;
    fb[744] = 1'h0;
    fb[745] = 1'h0;
    fb[746] = 1'h0;
    fb[747] = 1'h0;
    fb[748] = 1'h0;
    fb[749] = 1'h0;
    fb[750] = 1'h0;
    fb[751] = 1'h0;
    fb[752] = 1'h0;
    fb[753] = 1'h0;
    fb[754] = 1'h0;
    fb[755] = 1'h0;
    fb[756] = 1'h0;
    fb[757] = 1'h0;
    fb[758] = 1'h0;
    fb[759] = 1'h0;
    fb[760] = 1'h0;
    fb[761] = 1'h0;
    fb[762] = 1'h0;
    fb[763] = 1'h0;
    fb[764] = 1'h0;
    fb[765] = 1'h0;
    fb[766] = 1'h0;
    fb[767] = 1'h0;
    fb[768] = 1'h0;
    fb[769] = 1'h0;
    fb[770] = 1'h0;
    fb[771] = 1'h0;
    fb[772] = 1'h0;
    fb[773] = 1'h0;
    fb[774] = 1'h0;
    fb[775] = 1'h0;
    fb[776] = 1'h0;
    fb[777] = 1'h0;
    fb[778] = 1'h0;
    fb[779] = 1'h0;
    fb[780] = 1'h0;
    fb[781] = 1'h0;
    fb[782] = 1'h0;
    fb[783] = 1'h0;
    fb[784] = 1'h0;
    fb[785] = 1'h0;
    fb[786] = 1'h0;
    fb[787] = 1'h0;
    fb[788] = 1'h0;
    fb[789] = 1'h0;
    fb[790] = 1'h0;
    fb[791] = 1'h0;
    fb[792] = 1'h0;
    fb[793] = 1'h0;
    fb[794] = 1'h0;
    fb[795] = 1'h0;
    fb[796] = 1'h0;
    fb[797] = 1'h0;
    fb[798] = 1'h0;
    fb[799] = 1'h0;
    fb[800] = 1'h0;
    fb[801] = 1'h0;
    fb[802] = 1'h0;
    fb[803] = 1'h0;
    fb[804] = 1'h0;
    fb[805] = 1'h0;
    fb[806] = 1'h0;
    fb[807] = 1'h0;
    fb[808] = 1'h0;
    fb[809] = 1'h0;
    fb[810] = 1'h0;
    fb[811] = 1'h0;
    fb[812] = 1'h0;
    fb[813] = 1'h0;
    fb[814] = 1'h0;
    fb[815] = 1'h0;
    fb[816] = 1'h0;
    fb[817] = 1'h0;
    fb[818] = 1'h0;
    fb[819] = 1'h0;
    fb[820] = 1'h0;
    fb[821] = 1'h0;
    fb[822] = 1'h0;
    fb[823] = 1'h0;
    fb[824] = 1'h0;
    fb[825] = 1'h0;
    fb[826] = 1'h0;
    fb[827] = 1'h0;
    fb[828] = 1'h0;
    fb[829] = 1'h0;
    fb[830] = 1'h0;
    fb[831] = 1'h0;
    fb[832] = 1'h0;
    fb[833] = 1'h0;
    fb[834] = 1'h0;
    fb[835] = 1'h0;
    fb[836] = 1'h0;
    fb[837] = 1'h0;
    fb[838] = 1'h0;
    fb[839] = 1'h0;
    fb[840] = 1'h0;
    fb[841] = 1'h0;
    fb[842] = 1'h0;
    fb[843] = 1'h0;
    fb[844] = 1'h0;
    fb[845] = 1'h0;
    fb[846] = 1'h0;
    fb[847] = 1'h0;
    fb[848] = 1'h0;
    fb[849] = 1'h0;
    fb[850] = 1'h0;
    fb[851] = 1'h0;
    fb[852] = 1'h0;
    fb[853] = 1'h0;
    fb[854] = 1'h0;
    fb[855] = 1'h0;
    fb[856] = 1'h0;
    fb[857] = 1'h0;
    fb[858] = 1'h0;
    fb[859] = 1'h0;
    fb[860] = 1'h0;
    fb[861] = 1'h0;
    fb[862] = 1'h0;
    fb[863] = 1'h0;
    fb[864] = 1'h0;
    fb[865] = 1'h0;
    fb[866] = 1'h0;
    fb[867] = 1'h0;
    fb[868] = 1'h0;
    fb[869] = 1'h0;
    fb[870] = 1'h0;
    fb[871] = 1'h0;
    fb[872] = 1'h0;
    fb[873] = 1'h0;
    fb[874] = 1'h0;
    fb[875] = 1'h0;
    fb[876] = 1'h0;
    fb[877] = 1'h0;
    fb[878] = 1'h0;
    fb[879] = 1'h0;
    fb[880] = 1'h0;
    fb[881] = 1'h0;
    fb[882] = 1'h0;
    fb[883] = 1'h0;
    fb[884] = 1'h0;
    fb[885] = 1'h0;
    fb[886] = 1'h0;
    fb[887] = 1'h0;
    fb[888] = 1'h0;
    fb[889] = 1'h0;
    fb[890] = 1'h0;
    fb[891] = 1'h0;
    fb[892] = 1'h0;
    fb[893] = 1'h0;
    fb[894] = 1'h0;
    fb[895] = 1'h0;
    fb[896] = 1'h0;
    fb[897] = 1'h0;
    fb[898] = 1'h0;
    fb[899] = 1'h0;
    fb[900] = 1'h0;
    fb[901] = 1'h0;
    fb[902] = 1'h0;
    fb[903] = 1'h0;
    fb[904] = 1'h0;
    fb[905] = 1'h0;
    fb[906] = 1'h0;
    fb[907] = 1'h0;
    fb[908] = 1'h0;
    fb[909] = 1'h0;
    fb[910] = 1'h0;
    fb[911] = 1'h0;
    fb[912] = 1'h0;
    fb[913] = 1'h0;
    fb[914] = 1'h0;
    fb[915] = 1'h0;
    fb[916] = 1'h0;
    fb[917] = 1'h0;
    fb[918] = 1'h0;
    fb[919] = 1'h0;
    fb[920] = 1'h0;
    fb[921] = 1'h0;
    fb[922] = 1'h0;
    fb[923] = 1'h0;
    fb[924] = 1'h0;
    fb[925] = 1'h0;
    fb[926] = 1'h0;
    fb[927] = 1'h0;
    fb[928] = 1'h0;
    fb[929] = 1'h0;
    fb[930] = 1'h0;
    fb[931] = 1'h0;
    fb[932] = 1'h0;
    fb[933] = 1'h0;
    fb[934] = 1'h0;
    fb[935] = 1'h0;
    fb[936] = 1'h0;
    fb[937] = 1'h0;
    fb[938] = 1'h0;
    fb[939] = 1'h0;
    fb[940] = 1'h0;
    fb[941] = 1'h0;
    fb[942] = 1'h0;
    fb[943] = 1'h0;
    fb[944] = 1'h0;
    fb[945] = 1'h0;
    fb[946] = 1'h0;
    fb[947] = 1'h0;
    fb[948] = 1'h0;
    fb[949] = 1'h0;
    fb[950] = 1'h0;
    fb[951] = 1'h0;
    fb[952] = 1'h0;
    fb[953] = 1'h0;
    fb[954] = 1'h0;
    fb[955] = 1'h0;
    fb[956] = 1'h0;
    fb[957] = 1'h0;
    fb[958] = 1'h0;
    fb[959] = 1'h0;
    fb[960] = 1'h0;
    fb[961] = 1'h0;
    fb[962] = 1'h0;
    fb[963] = 1'h0;
    fb[964] = 1'h0;
    fb[965] = 1'h0;
    fb[966] = 1'h0;
    fb[967] = 1'h0;
    fb[968] = 1'h0;
    fb[969] = 1'h0;
    fb[970] = 1'h0;
    fb[971] = 1'h0;
    fb[972] = 1'h0;
    fb[973] = 1'h0;
    fb[974] = 1'h0;
    fb[975] = 1'h0;
    fb[976] = 1'h0;
    fb[977] = 1'h0;
    fb[978] = 1'h0;
    fb[979] = 1'h0;
    fb[980] = 1'h0;
    fb[981] = 1'h0;
    fb[982] = 1'h0;
    fb[983] = 1'h0;
    fb[984] = 1'h0;
    fb[985] = 1'h0;
    fb[986] = 1'h0;
    fb[987] = 1'h0;
    fb[988] = 1'h0;
    fb[989] = 1'h0;
    fb[990] = 1'h0;
    fb[991] = 1'h0;
    fb[992] = 1'h0;
    fb[993] = 1'h0;
    fb[994] = 1'h0;
    fb[995] = 1'h0;
    fb[996] = 1'h0;
    fb[997] = 1'h0;
    fb[998] = 1'h0;
    fb[999] = 1'h0;
    fb[1000] = 1'h0;
    fb[1001] = 1'h0;
    fb[1002] = 1'h0;
    fb[1003] = 1'h0;
    fb[1004] = 1'h0;
    fb[1005] = 1'h0;
    fb[1006] = 1'h0;
    fb[1007] = 1'h0;
    fb[1008] = 1'h0;
    fb[1009] = 1'h0;
    fb[1010] = 1'h0;
    fb[1011] = 1'h0;
    fb[1012] = 1'h0;
    fb[1013] = 1'h0;
    fb[1014] = 1'h0;
    fb[1015] = 1'h0;
    fb[1016] = 1'h0;
    fb[1017] = 1'h0;
    fb[1018] = 1'h0;
    fb[1019] = 1'h0;
    fb[1020] = 1'h0;
    fb[1021] = 1'h0;
    fb[1022] = 1'h0;
    fb[1023] = 1'h0;
  end
  reg [9:0] _0_;
  always @(posedge clk) begin
    _0_ <= fb_r_addr;
    if (fb_w_en) fb[fb_w_addr] <= fb_w_data;
  end
  assign fb_r_data = fb[_0_];
  assign \$10  = wb__adr[31:8] == (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *) 22'h300000;
  assign \$12  = wb__adr[31:8] == (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" *) 22'h300001;
  assign \$14  = wb__stb & (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *) wb__cyc;
  assign \$16  = wb__adr[31:8] == (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *) 22'h300000;
  assign \$18  = wb__adr[31:8] == (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" *) 22'h300001;
  assign \$20  = wb__stb & (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *) wb__cyc;
  assign \$22  = wb__adr[31:8] == (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *) 22'h300000;
  assign \$24  = wb__adr[31:8] == (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" *) 22'h300001;
  assign \$26  = wb__stb & (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *) wb__cyc;
  assign \$28  = wb__adr[31:8] == (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *) 22'h300000;
  assign \$2  = wb__stb & (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *) wb__cyc;
  assign \$30  = wb__adr[31:8] == (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" *) 22'h300001;
  assign \$32  = wb__stb & (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *) wb__cyc;
  assign \$34  = wb__adr[31:8] == (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *) 22'h300000;
  assign \$36  = wb__adr[31:8] == (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" *) 22'h300001;
  assign \$38  = + (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:293" *) fb_r_data;
  assign \$40  = wb__stb & (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *) wb__cyc;
  assign \$42  = wb__adr[31:8] == (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *) 22'h300000;
  assign \$44  = wb__adr[31:8] == (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" *) 22'h300001;
  assign \$46  = ~ (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:333" *) dvid_out_clk;
  assign \$48  = ~ (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:336" *) dvid_out[0];
  assign \$4  = wb__adr[31:8] == (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *) 22'h300000;
  assign \$50  = ~ (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:339" *) dvid_out[1];
  assign \$52  = ~ (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:342" *) dvid_out[2];
  assign \$6  = wb__adr[31:8] == (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" *) 22'h300001;
  assign \$8  = wb__stb & (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *) wb__cyc;
  always @(posedge clk)
    wb__ack <= \wb__ack$next ;
  always @(posedge clk)
    ack_r <= \ack_r$next ;
  \U$$0  \U$$0  (
    .reset(reset),
    .shift_clk(shift_clk)
  );
  always @* begin
    if (\initial ) begin end
    \ack_r$next  = ack_r;
    (* full_case = 32'd1 *)
    (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *)
    casez (\$2 )
      /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" */
      1'h1:
          (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *)
          casez ({ \$6 , \$4  })
            /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" */
            2'b?1:
                \ack_r$next  = 1'h0;
            /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" */
            2'b1?:
                \ack_r$next  = 1'h0;
          endcase
      /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:311" */
      default:
          \ack_r$next  = 1'h1;
    endcase
    (* src = "/home/konrad/dev/litex/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \ack_r$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\initial ) begin end
    fb_w_en = 1'h0;
    (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *)
    casez (\$8 )
      /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" */
      1'h1:
          (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *)
          casez ({ \$12 , \$10  })
            /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" */
            2'b?1:
                /* empty */;
            /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" */
            2'b1?:
                fb_w_en = wb__we;
          endcase
    endcase
  end
  always @* begin
    if (\initial ) begin end
    fb_w_addr = 10'h000;
    (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *)
    casez (\$14 )
      /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" */
      1'h1:
          (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *)
          casez ({ \$18 , \$16  })
            /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" */
            2'b?1:
                /* empty */;
            /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" */
            2'b1?:
                fb_w_addr = wb__adr[11:2];
          endcase
    endcase
  end
  always @* begin
    if (\initial ) begin end
    fb_w_data = 1'h0;
    (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *)
    casez (\$20 )
      /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" */
      1'h1:
          (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *)
          casez ({ \$24 , \$22  })
            /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" */
            2'b?1:
                /* empty */;
            /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" */
            2'b1?:
                fb_w_data = wb__dat_w[0];
          endcase
    endcase
  end
  always @* begin
    if (\initial ) begin end
    fb_r_addr = 10'h000;
    (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *)
    casez (\$26 )
      /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" */
      1'h1:
          (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *)
          casez ({ \$30 , \$28  })
            /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" */
            2'b?1:
                /* empty */;
            /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" */
            2'b1?:
                fb_r_addr = wb__adr[11:2];
          endcase
    endcase
  end
  always @* begin
    if (\initial ) begin end
    wb__dat_r = 32'd0;
    (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *)
    casez (\$32 )
      /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" */
      1'h1:
          (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *)
          casez ({ \$36 , \$34  })
            /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" */
            2'b?1:
                /* empty */;
            /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" */
            2'b1?:
                wb__dat_r = \$38 ;
          endcase
    endcase
  end
  always @* begin
    if (\initial ) begin end
    \wb__ack$next  = wb__ack;
    (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" *)
    casez (\$40 )
      /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:296" */
      1'h1:
          (* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" *)
          casez ({ \$44 , \$42  })
            /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:297" */
            2'b?1:
                /* empty */;
            /* src = "/mnt/extra/asic/wrapped_myip1/myip1/src/myip1_gol.py:303" */
            2'b1?:
                \wb__ack$next  = ack_r;
          endcase
    endcase
    (* src = "/home/konrad/dev/litex/nmigen/nmigen/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \wb__ack$next  = 1'h0;
    endcase
  end
  assign dvid_out_clk = 1'h0;
  assign dvid_out = 3'h0;
  assign buf_io_out[7] = \$52 ;
  assign buf_io_out[6] = 1'h0;
  assign buf_io_out[5] = \$50 ;
  assign buf_io_out[4] = 1'h0;
  assign buf_io_out[3] = \$48 ;
  assign buf_io_out[2] = 1'h0;
  assign buf_io_out[1] = \$46 ;
  assign buf_io_out[0] = 1'h0;
  assign rst = reset;
endmodule

